
heat1d_2oa: heat1d_2oa.stc
	rm -rf target/heat1d_2oa
	patus --outdir=target/heat1d_2oa --architecture=x86_64 --strategy=configs/simple.stg --create-validation=no heat1d_2oa.stc

heat2d_2oa: heat2d_2oa.stc
	rm -rf target/heat2d_2oa
	patus --outdir=target/heat2d_2oa --architecture=x86_64 --create-validation=no heat2d_2oa.stc

heat3d_2oa: heat3d_2oa.stc
	rm -rf target/heat3d_2oa
	patus --outdir=target/heat3d_2oa --architecture=x86_64 --create-validation=no heat3d_2oa.stc

wave1d_2oa: wave1d_2oa.stc
	rm -rf target/wave1d_2oa
	patus --outdir=target/wave1d_2oa --architecture=x86_64 --strategy=configs/simple.stg --create-validation=no wave1d_2oa.stc

wave2d_2oa: wave2d_2oa.stc
	rm -rf target/wave2d_2oa
	patus --outdir=target/wave2d_2oa --architecture=x86_64 --create-validation=no wave2d_2oa.stc

wave3d_2oa: wave3d_2oa.stc
	rm -rf target/wave3d_2oa
	patus --outdir=target/wave3d_2oa --architecture=x86_64 --create-validation=no wave3d_2oa.stc

lapla1d_2oa: lapla1d_2oa.stc
	rm -rf target/lapla1d_2oa
	patus --outdir=target/lapla1d_2oa --architecture=x86_64 --strategy=configs/simple.stg --create-validation=no lapla1d_2oa.stc

lapla2d_2oa: lapla2d_2oa.stc
	rm -rf target/lapla2d_2oa
	patus --outdir=target/lapla2d_2oa --architecture=x86_64 --create-validation=no lapla2d_2oa.stc

lapla3d_2oa: lapla3d_2oa.stc
	rm -rf target/lapla3d_2oa
	patus --outdir=target/lapla3d_2oa --architecture=x86_64 --create-validation=no lapla3d_2oa.stc

clean:
	rm -rf target/*

